# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликовано'), (3, 'Заархивировано')], default=1, verbose_name='Статус объявления'),
        ),
    ]
